In [38]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import glob
import xarray as xr
import sys, os
from utils import *
from config import *
from data import obs_sonde, tropoe_sonde

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [42]:
c = pd.read_csv('../clear_sky_sgp_sounding_times.csv')

In [43]:
c

     Unnamed: 0      date  time  hr_dec  perc_cloud
0             0  20240701  1128   11.50         0.0
1             1  20250101  1854   19.00         0.0
2             2  20250101  2326   23.50         0.0
3             3  20250103  2330   23.50         0.0
4             4  20250105  2326   23.50         0.0
..          ...       ...   ...     ...         ...
98           98  20251227  2330   23.50         0.0
99           99  20251229  1908   19.25         0.0
100         100  20251229  2330   23.50         0.0
101         101  20251230  1730   17.50         0.0
102         102  20251231  2325   23.50         0.0

[103 rows x 5 columns]

In [ ]:
for i,d in enumerate(c['date']):

In [40]:
Ch2_bands = [1,6,12]
date = '20250101'
time = '1854'  #Omit minutes (only HH)

tmstmps = [f'{d}_{c["time"][i]}' for i,d in enumerate(c['date'][:20])]
retrievals = ['Ch1']
retrievals.extend([f'Ch2-{i}' for i in ch2_bands])

df = pd.DataFrame(index=tmstmps, columns=retrievals)
df.index.name = 'Timestamp'

rets = ['Ch1']
rets.extend([f'Ch2-band{i}' for i in Ch2_bands])

add = pd.DataFrame({ret: rmse for ret, rmse in zip(rets,rmse_Td)},
                   index = [f'{date}_{time}'])

df.update(add)
df

,Ch1,Ch2-band1,Ch2-band2,Ch2-band3,Ch2-band4,Ch2-band5,Ch2-band6,Ch2-band7,Ch2-band8,Ch2-band9,Ch2-band10,Ch2-band11,Ch2-band12
Timestamp,,,,,,,,,,,,,
20240701_1128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250101_1854,5.765898,4.24567,NaN,NaN,NaN,NaN,4.099233,NaN,NaN,NaN,NaN,NaN,3.569063
20250101_2326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250103_2330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250105_2326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250107_2337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250108_1730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250109_2327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250110_1730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250110_1927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250111_2325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250112_1730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250116_1730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250117_2328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250121_1851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250121_2328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250122_1730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250123_2329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250124_1730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20250125_2340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df.to_csv(f'{retrieval_stats_dir}/Td_RMSE.csv')

In [ ]:

print(a)

['Ch1', 'Ch2-band1', 'Ch2-band2', 'Ch2-band3', 'Ch2-band4', 'Ch2-band5', 'Ch2-band6', 'Ch2-band7', 'Ch2-band8', 'Ch2-band9', 'Ch2-band10', 'Ch2-band11', 'Ch2-band12']

In [21]:
[f'Ch2-{i}' for i in ch2_bands]

['Ch2-band1',
 'Ch2-band2',
 'Ch2-band3',
 'Ch2-band4',
 'Ch2-band5',
 'Ch2-band6',
 'Ch2-band7',
 'Ch2-band8',
 'Ch2-band9',
 'Ch2-band10',
 'Ch2-band11',
 'Ch2-band12']

In [15]:
a

In [ ]:
RMSE =